version: '3.8'

services:
  postgres:
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
  cloudflared:
    image: 'cloudflare/cloudflared:latest'
    command: 'tunnel run'
    environment:
      TUNNEL_TOKEN: '${CLOUDFLARED_TOKEN}'
